// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GameMain.Generate.FlatBuffers
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct DictIntFloat : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static DictIntFloat GetRootAsDictIntFloat(ByteBuffer _bb) { return GetRootAsDictIntFloat(_bb, new DictIntFloat()); }
  public static DictIntFloat GetRootAsDictIntFloat(ByteBuffer _bb, DictIntFloat obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DictIntFloat __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Key { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public float Value { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<GameMain.Generate.FlatBuffers.DictIntFloat> CreateDictIntFloat(FlatBufferBuilder builder,
      int key = 0,
      float value = 0.0f) {
    builder.StartTable(2);
    DictIntFloat.AddValue(builder, value);
    DictIntFloat.AddKey(builder, key);
    return DictIntFloat.EndDictIntFloat(builder);
  }

  public static void StartDictIntFloat(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddKey(FlatBufferBuilder builder, int key) { builder.AddInt(0, key, 0); }
  public static void AddValue(FlatBufferBuilder builder, float value) { builder.AddFloat(1, value, 0.0f); }
  public static Offset<GameMain.Generate.FlatBuffers.DictIntFloat> EndDictIntFloat(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<GameMain.Generate.FlatBuffers.DictIntFloat>(o);
  }
}


static public class DictIntFloatVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Key*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Value*/, 4 /*float*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
