// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GameMain.Generate.FlatBuffers
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FB_bullet_bullet : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static FB_bullet_bullet GetRootAsFB_bullet_bullet(ByteBuffer _bb) { return GetRootAsFB_bullet_bullet(_bb, new FB_bullet_bullet()); }
  public static FB_bullet_bullet GetRootAsFB_bullet_bullet(ByteBuffer _bb, FB_bullet_bullet obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FB_bullet_bullet __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int ID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public float BulletSpeed { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float BulletInterval { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public bool IsCanStone { get { int o = __p.__offset(10); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public string ResName { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetResNameBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetResNameBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetResNameArray() { return __p.__vector_as_array<byte>(12); }

  public static Offset<GameMain.Generate.FlatBuffers.FB_bullet_bullet> CreateFB_bullet_bullet(FlatBufferBuilder builder,
      int ID = 0,
      float bulletSpeed = 0.0f,
      float bulletInterval = 0.0f,
      bool IsCanStone = false,
      StringOffset resNameOffset = default(StringOffset)) {
    builder.StartTable(5);
    FB_bullet_bullet.AddResName(builder, resNameOffset);
    FB_bullet_bullet.AddBulletInterval(builder, bulletInterval);
    FB_bullet_bullet.AddBulletSpeed(builder, bulletSpeed);
    FB_bullet_bullet.AddID(builder, ID);
    FB_bullet_bullet.AddIsCanStone(builder, IsCanStone);
    return FB_bullet_bullet.EndFB_bullet_bullet(builder);
  }

  public static void StartFB_bullet_bullet(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddID(FlatBufferBuilder builder, int iD) { builder.AddInt(0, iD, 0); }
  public static void AddBulletSpeed(FlatBufferBuilder builder, float bulletSpeed) { builder.AddFloat(1, bulletSpeed, 0.0f); }
  public static void AddBulletInterval(FlatBufferBuilder builder, float bulletInterval) { builder.AddFloat(2, bulletInterval, 0.0f); }
  public static void AddIsCanStone(FlatBufferBuilder builder, bool isCanStone) { builder.AddBool(3, isCanStone, false); }
  public static void AddResName(FlatBufferBuilder builder, StringOffset resNameOffset) { builder.AddOffset(4, resNameOffset.Value, 0); }
  public static Offset<GameMain.Generate.FlatBuffers.FB_bullet_bullet> EndFB_bullet_bullet(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<GameMain.Generate.FlatBuffers.FB_bullet_bullet>(o);
  }
}


static public class FB_bullet_bulletVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ID*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*BulletSpeed*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*BulletInterval*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*IsCanStone*/, 1 /*bool*/, 1, false)
      && verifier.VerifyString(tablePos, 12 /*ResName*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
