// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GameMain.Generate.FlatBuffers
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FB_map_mapNormal : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static FB_map_mapNormal GetRootAsFB_map_mapNormal(ByteBuffer _bb) { return GetRootAsFB_map_mapNormal(_bb, new FB_map_mapNormal()); }
  public static FB_map_mapNormal GetRootAsFB_map_mapNormal(ByteBuffer _bb, FB_map_mapNormal obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FB_map_mapNormal __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int ID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Y0(int j) { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int Y0Length { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetY0Bytes() { return __p.__vector_as_span<int>(6, 4); }
#else
  public ArraySegment<byte>? GetY0Bytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public int[] GetY0Array() { return __p.__vector_as_array<int>(6); }
  public int Y1(int j) { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int Y1Length { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetY1Bytes() { return __p.__vector_as_span<int>(8, 4); }
#else
  public ArraySegment<byte>? GetY1Bytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public int[] GetY1Array() { return __p.__vector_as_array<int>(8); }
  public int Y2(int j) { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int Y2Length { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetY2Bytes() { return __p.__vector_as_span<int>(10, 4); }
#else
  public ArraySegment<byte>? GetY2Bytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public int[] GetY2Array() { return __p.__vector_as_array<int>(10); }
  public int Y3(int j) { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int Y3Length { get { int o = __p.__offset(12); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetY3Bytes() { return __p.__vector_as_span<int>(12, 4); }
#else
  public ArraySegment<byte>? GetY3Bytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public int[] GetY3Array() { return __p.__vector_as_array<int>(12); }
  public int Y4(int j) { int o = __p.__offset(14); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int Y4Length { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetY4Bytes() { return __p.__vector_as_span<int>(14, 4); }
#else
  public ArraySegment<byte>? GetY4Bytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public int[] GetY4Array() { return __p.__vector_as_array<int>(14); }
  public int Y5(int j) { int o = __p.__offset(16); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int Y5Length { get { int o = __p.__offset(16); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetY5Bytes() { return __p.__vector_as_span<int>(16, 4); }
#else
  public ArraySegment<byte>? GetY5Bytes() { return __p.__vector_as_arraysegment(16); }
#endif
  public int[] GetY5Array() { return __p.__vector_as_array<int>(16); }
  public int Y6(int j) { int o = __p.__offset(18); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int Y6Length { get { int o = __p.__offset(18); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetY6Bytes() { return __p.__vector_as_span<int>(18, 4); }
#else
  public ArraySegment<byte>? GetY6Bytes() { return __p.__vector_as_arraysegment(18); }
#endif
  public int[] GetY6Array() { return __p.__vector_as_array<int>(18); }
  public int Y7(int j) { int o = __p.__offset(20); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int Y7Length { get { int o = __p.__offset(20); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetY7Bytes() { return __p.__vector_as_span<int>(20, 4); }
#else
  public ArraySegment<byte>? GetY7Bytes() { return __p.__vector_as_arraysegment(20); }
#endif
  public int[] GetY7Array() { return __p.__vector_as_array<int>(20); }
  public int Y8(int j) { int o = __p.__offset(22); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int Y8Length { get { int o = __p.__offset(22); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetY8Bytes() { return __p.__vector_as_span<int>(22, 4); }
#else
  public ArraySegment<byte>? GetY8Bytes() { return __p.__vector_as_arraysegment(22); }
#endif
  public int[] GetY8Array() { return __p.__vector_as_array<int>(22); }
  public int Y9(int j) { int o = __p.__offset(24); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int Y9Length { get { int o = __p.__offset(24); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetY9Bytes() { return __p.__vector_as_span<int>(24, 4); }
#else
  public ArraySegment<byte>? GetY9Bytes() { return __p.__vector_as_arraysegment(24); }
#endif
  public int[] GetY9Array() { return __p.__vector_as_array<int>(24); }
  public int Y10(int j) { int o = __p.__offset(26); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int Y10Length { get { int o = __p.__offset(26); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetY10Bytes() { return __p.__vector_as_span<int>(26, 4); }
#else
  public ArraySegment<byte>? GetY10Bytes() { return __p.__vector_as_arraysegment(26); }
#endif
  public int[] GetY10Array() { return __p.__vector_as_array<int>(26); }
  public int Y11(int j) { int o = __p.__offset(28); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int Y11Length { get { int o = __p.__offset(28); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetY11Bytes() { return __p.__vector_as_span<int>(28, 4); }
#else
  public ArraySegment<byte>? GetY11Bytes() { return __p.__vector_as_arraysegment(28); }
#endif
  public int[] GetY11Array() { return __p.__vector_as_array<int>(28); }
  public int Y12(int j) { int o = __p.__offset(30); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int Y12Length { get { int o = __p.__offset(30); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetY12Bytes() { return __p.__vector_as_span<int>(30, 4); }
#else
  public ArraySegment<byte>? GetY12Bytes() { return __p.__vector_as_arraysegment(30); }
#endif
  public int[] GetY12Array() { return __p.__vector_as_array<int>(30); }

  public static Offset<GameMain.Generate.FlatBuffers.FB_map_mapNormal> CreateFB_map_mapNormal(FlatBufferBuilder builder,
      int ID = 0,
      VectorOffset Y0Offset = default(VectorOffset),
      VectorOffset Y1Offset = default(VectorOffset),
      VectorOffset Y2Offset = default(VectorOffset),
      VectorOffset Y3Offset = default(VectorOffset),
      VectorOffset Y4Offset = default(VectorOffset),
      VectorOffset Y5Offset = default(VectorOffset),
      VectorOffset Y6Offset = default(VectorOffset),
      VectorOffset Y7Offset = default(VectorOffset),
      VectorOffset Y8Offset = default(VectorOffset),
      VectorOffset Y9Offset = default(VectorOffset),
      VectorOffset Y10Offset = default(VectorOffset),
      VectorOffset Y11Offset = default(VectorOffset),
      VectorOffset Y12Offset = default(VectorOffset)) {
    builder.StartTable(14);
    FB_map_mapNormal.AddY12(builder, Y12Offset);
    FB_map_mapNormal.AddY11(builder, Y11Offset);
    FB_map_mapNormal.AddY10(builder, Y10Offset);
    FB_map_mapNormal.AddY9(builder, Y9Offset);
    FB_map_mapNormal.AddY8(builder, Y8Offset);
    FB_map_mapNormal.AddY7(builder, Y7Offset);
    FB_map_mapNormal.AddY6(builder, Y6Offset);
    FB_map_mapNormal.AddY5(builder, Y5Offset);
    FB_map_mapNormal.AddY4(builder, Y4Offset);
    FB_map_mapNormal.AddY3(builder, Y3Offset);
    FB_map_mapNormal.AddY2(builder, Y2Offset);
    FB_map_mapNormal.AddY1(builder, Y1Offset);
    FB_map_mapNormal.AddY0(builder, Y0Offset);
    FB_map_mapNormal.AddID(builder, ID);
    return FB_map_mapNormal.EndFB_map_mapNormal(builder);
  }

  public static void StartFB_map_mapNormal(FlatBufferBuilder builder) { builder.StartTable(14); }
  public static void AddID(FlatBufferBuilder builder, int iD) { builder.AddInt(0, iD, 0); }
  public static void AddY0(FlatBufferBuilder builder, VectorOffset y0Offset) { builder.AddOffset(1, y0Offset.Value, 0); }
  public static VectorOffset CreateY0Vector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateY0VectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateY0VectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateY0VectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartY0Vector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddY1(FlatBufferBuilder builder, VectorOffset y1Offset) { builder.AddOffset(2, y1Offset.Value, 0); }
  public static VectorOffset CreateY1Vector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateY1VectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateY1VectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateY1VectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartY1Vector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddY2(FlatBufferBuilder builder, VectorOffset y2Offset) { builder.AddOffset(3, y2Offset.Value, 0); }
  public static VectorOffset CreateY2Vector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateY2VectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateY2VectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateY2VectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartY2Vector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddY3(FlatBufferBuilder builder, VectorOffset y3Offset) { builder.AddOffset(4, y3Offset.Value, 0); }
  public static VectorOffset CreateY3Vector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateY3VectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateY3VectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateY3VectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartY3Vector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddY4(FlatBufferBuilder builder, VectorOffset y4Offset) { builder.AddOffset(5, y4Offset.Value, 0); }
  public static VectorOffset CreateY4Vector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateY4VectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateY4VectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateY4VectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartY4Vector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddY5(FlatBufferBuilder builder, VectorOffset y5Offset) { builder.AddOffset(6, y5Offset.Value, 0); }
  public static VectorOffset CreateY5Vector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateY5VectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateY5VectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateY5VectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartY5Vector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddY6(FlatBufferBuilder builder, VectorOffset y6Offset) { builder.AddOffset(7, y6Offset.Value, 0); }
  public static VectorOffset CreateY6Vector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateY6VectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateY6VectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateY6VectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartY6Vector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddY7(FlatBufferBuilder builder, VectorOffset y7Offset) { builder.AddOffset(8, y7Offset.Value, 0); }
  public static VectorOffset CreateY7Vector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateY7VectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateY7VectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateY7VectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartY7Vector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddY8(FlatBufferBuilder builder, VectorOffset y8Offset) { builder.AddOffset(9, y8Offset.Value, 0); }
  public static VectorOffset CreateY8Vector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateY8VectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateY8VectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateY8VectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartY8Vector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddY9(FlatBufferBuilder builder, VectorOffset y9Offset) { builder.AddOffset(10, y9Offset.Value, 0); }
  public static VectorOffset CreateY9Vector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateY9VectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateY9VectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateY9VectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartY9Vector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddY10(FlatBufferBuilder builder, VectorOffset y10Offset) { builder.AddOffset(11, y10Offset.Value, 0); }
  public static VectorOffset CreateY10Vector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateY10VectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateY10VectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateY10VectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartY10Vector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddY11(FlatBufferBuilder builder, VectorOffset y11Offset) { builder.AddOffset(12, y11Offset.Value, 0); }
  public static VectorOffset CreateY11Vector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateY11VectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateY11VectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateY11VectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartY11Vector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddY12(FlatBufferBuilder builder, VectorOffset y12Offset) { builder.AddOffset(13, y12Offset.Value, 0); }
  public static VectorOffset CreateY12Vector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateY12VectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateY12VectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateY12VectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartY12Vector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<GameMain.Generate.FlatBuffers.FB_map_mapNormal> EndFB_map_mapNormal(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<GameMain.Generate.FlatBuffers.FB_map_mapNormal>(o);
  }
}


static public class FB_map_mapNormalVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ID*/, 4 /*int*/, 4, false)
      && verifier.VerifyVectorOfData(tablePos, 6 /*Y0*/, 4 /*int*/, false)
      && verifier.VerifyVectorOfData(tablePos, 8 /*Y1*/, 4 /*int*/, false)
      && verifier.VerifyVectorOfData(tablePos, 10 /*Y2*/, 4 /*int*/, false)
      && verifier.VerifyVectorOfData(tablePos, 12 /*Y3*/, 4 /*int*/, false)
      && verifier.VerifyVectorOfData(tablePos, 14 /*Y4*/, 4 /*int*/, false)
      && verifier.VerifyVectorOfData(tablePos, 16 /*Y5*/, 4 /*int*/, false)
      && verifier.VerifyVectorOfData(tablePos, 18 /*Y6*/, 4 /*int*/, false)
      && verifier.VerifyVectorOfData(tablePos, 20 /*Y7*/, 4 /*int*/, false)
      && verifier.VerifyVectorOfData(tablePos, 22 /*Y8*/, 4 /*int*/, false)
      && verifier.VerifyVectorOfData(tablePos, 24 /*Y9*/, 4 /*int*/, false)
      && verifier.VerifyVectorOfData(tablePos, 26 /*Y10*/, 4 /*int*/, false)
      && verifier.VerifyVectorOfData(tablePos, 28 /*Y11*/, 4 /*int*/, false)
      && verifier.VerifyVectorOfData(tablePos, 30 /*Y12*/, 4 /*int*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
