// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GameMain.Generate.FlatBuffers
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FB_prop_prop : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static FB_prop_prop GetRootAsFB_prop_prop(ByteBuffer _bb) { return GetRootAsFB_prop_prop(_bb, new FB_prop_prop()); }
  public static FB_prop_prop GetRootAsFB_prop_prop(ByteBuffer _bb, FB_prop_prop obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FB_prop_prop __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<GameMain.Generate.FlatBuffers.FB_prop_prop> CreateFB_prop_prop(FlatBufferBuilder builder,
      int id = 0,
      StringOffset NameOffset = default(StringOffset)) {
    builder.StartTable(2);
    FB_prop_prop.AddName(builder, NameOffset);
    FB_prop_prop.AddId(builder, id);
    return FB_prop_prop.EndFB_prop_prop(builder);
  }

  public static void StartFB_prop_prop(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
  public static Offset<GameMain.Generate.FlatBuffers.FB_prop_prop> EndFB_prop_prop(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<GameMain.Generate.FlatBuffers.FB_prop_prop>(o);
  }
}


static public class FB_prop_propVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*Name*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
