// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GameMain.Generate.FlatBuffers
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FB_reward_sidebar : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static FB_reward_sidebar GetRootAsFB_reward_sidebar(ByteBuffer _bb) { return GetRootAsFB_reward_sidebar(_bb, new FB_reward_sidebar()); }
  public static FB_reward_sidebar GetRootAsFB_reward_sidebar(ByteBuffer _bb, FB_reward_sidebar obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FB_reward_sidebar __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int ID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int RewardType { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int RewardValue(int j) { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int RewardValueLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetRewardValueBytes() { return __p.__vector_as_span<int>(8, 4); }
#else
  public ArraySegment<byte>? GetRewardValueBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public int[] GetRewardValueArray() { return __p.__vector_as_array<int>(8); }
  public string Des { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDesBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetDesBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetDesArray() { return __p.__vector_as_array<byte>(10); }
  public string AssetName { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetAssetNameBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetAssetNameBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetAssetNameArray() { return __p.__vector_as_array<byte>(12); }

  public static Offset<GameMain.Generate.FlatBuffers.FB_reward_sidebar> CreateFB_reward_sidebar(FlatBufferBuilder builder,
      int ID = 0,
      int RewardType = 0,
      VectorOffset RewardValueOffset = default(VectorOffset),
      StringOffset DesOffset = default(StringOffset),
      StringOffset AssetNameOffset = default(StringOffset)) {
    builder.StartTable(5);
    FB_reward_sidebar.AddAssetName(builder, AssetNameOffset);
    FB_reward_sidebar.AddDes(builder, DesOffset);
    FB_reward_sidebar.AddRewardValue(builder, RewardValueOffset);
    FB_reward_sidebar.AddRewardType(builder, RewardType);
    FB_reward_sidebar.AddID(builder, ID);
    return FB_reward_sidebar.EndFB_reward_sidebar(builder);
  }

  public static void StartFB_reward_sidebar(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddID(FlatBufferBuilder builder, int iD) { builder.AddInt(0, iD, 0); }
  public static void AddRewardType(FlatBufferBuilder builder, int rewardType) { builder.AddInt(1, rewardType, 0); }
  public static void AddRewardValue(FlatBufferBuilder builder, VectorOffset rewardValueOffset) { builder.AddOffset(2, rewardValueOffset.Value, 0); }
  public static VectorOffset CreateRewardValueVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateRewardValueVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateRewardValueVectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateRewardValueVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartRewardValueVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddDes(FlatBufferBuilder builder, StringOffset desOffset) { builder.AddOffset(3, desOffset.Value, 0); }
  public static void AddAssetName(FlatBufferBuilder builder, StringOffset assetNameOffset) { builder.AddOffset(4, assetNameOffset.Value, 0); }
  public static Offset<GameMain.Generate.FlatBuffers.FB_reward_sidebar> EndFB_reward_sidebar(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<GameMain.Generate.FlatBuffers.FB_reward_sidebar>(o);
  }
}


static public class FB_reward_sidebarVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ID*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*RewardType*/, 4 /*int*/, 4, false)
      && verifier.VerifyVectorOfData(tablePos, 8 /*RewardValue*/, 4 /*int*/, false)
      && verifier.VerifyString(tablePos, 10 /*Des*/, false)
      && verifier.VerifyString(tablePos, 12 /*AssetName*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
