// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GameMain.Generate.FlatBuffers
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FB_reward_sidebar_Array : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static FB_reward_sidebar_Array GetRootAsFB_reward_sidebar_Array(ByteBuffer _bb) { return GetRootAsFB_reward_sidebar_Array(_bb, new FB_reward_sidebar_Array()); }
  public static FB_reward_sidebar_Array GetRootAsFB_reward_sidebar_Array(ByteBuffer _bb, FB_reward_sidebar_Array obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyFB_reward_sidebar_Array(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, FB_reward_sidebar_ArrayVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FB_reward_sidebar_Array __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public GameMain.Generate.FlatBuffers.FB_reward_sidebar? Datas(int j) { int o = __p.__offset(4); return o != 0 ? (GameMain.Generate.FlatBuffers.FB_reward_sidebar?)(new GameMain.Generate.FlatBuffers.FB_reward_sidebar()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DatasLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<GameMain.Generate.FlatBuffers.FB_reward_sidebar_Array> CreateFB_reward_sidebar_Array(FlatBufferBuilder builder,
      VectorOffset datasOffset = default(VectorOffset)) {
    builder.StartTable(1);
    FB_reward_sidebar_Array.AddDatas(builder, datasOffset);
    return FB_reward_sidebar_Array.EndFB_reward_sidebar_Array(builder);
  }

  public static void StartFB_reward_sidebar_Array(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddDatas(FlatBufferBuilder builder, VectorOffset datasOffset) { builder.AddOffset(0, datasOffset.Value, 0); }
  public static VectorOffset CreateDatasVector(FlatBufferBuilder builder, Offset<GameMain.Generate.FlatBuffers.FB_reward_sidebar>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDatasVectorBlock(FlatBufferBuilder builder, Offset<GameMain.Generate.FlatBuffers.FB_reward_sidebar>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDatasVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<GameMain.Generate.FlatBuffers.FB_reward_sidebar>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDatasVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<GameMain.Generate.FlatBuffers.FB_reward_sidebar>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartDatasVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<GameMain.Generate.FlatBuffers.FB_reward_sidebar_Array> EndFB_reward_sidebar_Array(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<GameMain.Generate.FlatBuffers.FB_reward_sidebar_Array>(o);
  }
  public static void FinishFB_reward_sidebar_ArrayBuffer(FlatBufferBuilder builder, Offset<GameMain.Generate.FlatBuffers.FB_reward_sidebar_Array> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedFB_reward_sidebar_ArrayBuffer(FlatBufferBuilder builder, Offset<GameMain.Generate.FlatBuffers.FB_reward_sidebar_Array> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class FB_reward_sidebar_ArrayVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*Datas*/, GameMain.Generate.FlatBuffers.FB_reward_sidebarVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
