// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GameMain.Generate.FlatBuffers
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FB_tank_enemy : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static FB_tank_enemy GetRootAsFB_tank_enemy(ByteBuffer _bb) { return GetRootAsFB_tank_enemy(_bb, new FB_tank_enemy()); }
  public static FB_tank_enemy GetRootAsFB_tank_enemy(ByteBuffer _bb, FB_tank_enemy obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FB_tank_enemy __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int ID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<GameMain.Generate.FlatBuffers.FB_tank_enemy> CreateFB_tank_enemy(FlatBufferBuilder builder,
      int ID = 0) {
    builder.StartTable(1);
    FB_tank_enemy.AddID(builder, ID);
    return FB_tank_enemy.EndFB_tank_enemy(builder);
  }

  public static void StartFB_tank_enemy(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddID(FlatBufferBuilder builder, int iD) { builder.AddInt(0, iD, 0); }
  public static Offset<GameMain.Generate.FlatBuffers.FB_tank_enemy> EndFB_tank_enemy(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<GameMain.Generate.FlatBuffers.FB_tank_enemy>(o);
  }
}


static public class FB_tank_enemyVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ID*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
