using System;
using UnityEditor;
using UnityEngine;

[Serializable]
public class GenerationConfig
{
    // EditorPrefs 键名常量
    private static string PREFS_KEY_PREFIX = $"{Application.dataPath}_";
    private static string KEY_EXCEL_FOLDER = PREFS_KEY_PREFIX + "ExcelFolderPath";
    private static string KEY_CUSTOM_DATA_TYPE_FILE_PATH = PREFS_KEY_PREFIX + "CustomDataTypeFilePath";
    private static string KEY_OUTPUT_PATH = PREFS_KEY_PREFIX + "OutputPath";
    private static string KEY_DATA_PATH = PREFS_KEY_PREFIX + "DataPathOutputPath";
    private static string KEY_CS_PATH = PREFS_KEY_PREFIX + "CsOutputPath";
    private static string KEY_FLATC_PATH = PREFS_KEY_PREFIX + "FlatcPath";
    private static string KEY_COPY_BYTES_PATH = PREFS_KEY_PREFIX + "CopyBytesPath";
    private static string KEY_FIELD_COMMENT_INDEX = PREFS_KEY_PREFIX + "FieldCommentIndex";
    private static string KEY_FIELD_NAME_INDEX = PREFS_KEY_PREFIX + "FieldNameIndex";
    private static string KEY_FIELD_TYPE_INDEX = PREFS_KEY_PREFIX + "FieldTypeIndex";
    private static string KEY_FIELD_TAG_INDEX = PREFS_KEY_PREFIX + "FieldTagIndex";
    private static string KEY_DATA_START_INDEX = PREFS_KEY_PREFIX + "DataStartIndex";

    // 默认值
    private static string defaultExcelFolderPath = "Assets/../excels";
    private string defaultCustomTypeFilePath = defaultExcelFolderPath+"/_CustomDataType.fbs";
    private string defaultOutputPath = "Assets/Scripts";
    private string defaultDataPathOutputPath = "Assets/AutoGenerated/FlatBuffersDataFile";
    private string defaultCsOutputPath = "Assets/AutoGenerated/Scripts";
    private string defaultFlatcPath = Application.dataPath + "/../_Tools/flatc.exe";
    private string defaultCopyBytesPath = Application.dataPath + "/Resources/fb";
    private int defaultFieldCommentIndex = 3;
    private int defaultFieldNameIndex = 5;
    private int defaultFieldTypeIndex = 6;
    private int defaultFieldTagIndex = 7;
    private int defaultDataStartIndex = 8;

    // 属性封装，关联 EditorPrefs
    public string ExcelFolderPath
    {
        get => EditorPrefs.GetString(KEY_EXCEL_FOLDER, defaultExcelFolderPath);
        set => EditorPrefs.SetString(KEY_EXCEL_FOLDER, value);
    }

    public string CustomDataTypeFilePath
    {
        get => EditorPrefs.GetString(KEY_CUSTOM_DATA_TYPE_FILE_PATH, defaultCustomTypeFilePath);
        set => EditorPrefs.SetString(KEY_CUSTOM_DATA_TYPE_FILE_PATH, value);
    }

    public string OutputPath
    {
        get => EditorPrefs.GetString(KEY_OUTPUT_PATH, defaultOutputPath);
        set => EditorPrefs.SetString(KEY_OUTPUT_PATH, value);
    }

    public string DataPathOutputPath
    {
        get => EditorPrefs.GetString(KEY_DATA_PATH, defaultDataPathOutputPath);
        set => EditorPrefs.SetString(KEY_DATA_PATH, value);
    }

    public string CsOutputPath
    {
        get => EditorPrefs.GetString(KEY_CS_PATH, defaultCsOutputPath);
        set => EditorPrefs.SetString(KEY_CS_PATH, value);
    }

    public string FlatcPath
    {
        get => EditorPrefs.GetString(KEY_FLATC_PATH, defaultFlatcPath);
        set => EditorPrefs.SetString(KEY_FLATC_PATH, value);
    }

    public string CopyBytesPath
    {
        get => EditorPrefs.GetString(KEY_COPY_BYTES_PATH, defaultCopyBytesPath);
        set => EditorPrefs.SetString(KEY_COPY_BYTES_PATH, value);
    }

    public int FieldCommentIndex
    {
        get => EditorPrefs.GetInt(KEY_FIELD_COMMENT_INDEX, defaultFieldCommentIndex);
        set => EditorPrefs.SetInt(KEY_FIELD_COMMENT_INDEX, value);
    }

    public int FieldNameIndex
    {
        get => EditorPrefs.GetInt(KEY_FIELD_NAME_INDEX, defaultFieldNameIndex);
        set => EditorPrefs.SetInt(KEY_FIELD_NAME_INDEX, value);
    }

    public int FieldTypeIndex
    {
        get => EditorPrefs.GetInt(KEY_FIELD_TYPE_INDEX, defaultFieldTypeIndex);
        set => EditorPrefs.SetInt(KEY_FIELD_TYPE_INDEX, value);
    }

    public int FieldTagIndex
    {
        get => EditorPrefs.GetInt(KEY_FIELD_TAG_INDEX, defaultFieldTagIndex);
        set => EditorPrefs.SetInt(KEY_FIELD_TAG_INDEX, value);
    }
    
    public int DataStartIndex
    {
        get => EditorPrefs.GetInt(KEY_DATA_START_INDEX, defaultDataStartIndex);
        set => EditorPrefs.SetInt(KEY_DATA_START_INDEX, value);
    }

    [NonSerialized]
    public bool flatcAvailable = false;

    // 重置为默认值的方法
    public void ResetToDefaults()
    {
        ExcelFolderPath = defaultExcelFolderPath;
        CustomDataTypeFilePath = defaultCustomTypeFilePath;
        OutputPath = defaultOutputPath;
        DataPathOutputPath = defaultDataPathOutputPath;
        CsOutputPath = defaultCsOutputPath;
        FlatcPath = defaultFlatcPath;
        CopyBytesPath = defaultCopyBytesPath;
        FieldCommentIndex = defaultFieldCommentIndex;
        FieldNameIndex = defaultFieldNameIndex;
        FieldTypeIndex = defaultFieldTypeIndex;
        DataStartIndex = defaultDataStartIndex;
    }

    // 清除所有保存的设置
    public static void ClearAllSettings()
    {
        EditorPrefs.DeleteKey(KEY_EXCEL_FOLDER);
        EditorPrefs.DeleteKey(KEY_OUTPUT_PATH);
        EditorPrefs.DeleteKey(KEY_DATA_PATH);
        EditorPrefs.DeleteKey(KEY_CS_PATH);
        EditorPrefs.DeleteKey(KEY_FLATC_PATH);
        EditorPrefs.DeleteKey(KEY_COPY_BYTES_PATH);
        EditorPrefs.DeleteKey(KEY_FIELD_COMMENT_INDEX);
        EditorPrefs.DeleteKey(KEY_FIELD_NAME_INDEX);
        EditorPrefs.DeleteKey(KEY_FIELD_TYPE_INDEX);
        EditorPrefs.DeleteKey(KEY_FIELD_TAG_INDEX);
        EditorPrefs.DeleteKey(KEY_DATA_START_INDEX);
    }
}

[Serializable]
public class ExcelTableData
{
    public string tableName;
    public string workbookName;
    public string[] fieldComments;
    public string[] fieldNames;
    public string[] fieldTypes;
    public string[][] dataRows;
}