using System;
using UnityEditor;
using UnityEngine;

[Serializable]
public class GenerationConfig
{
    // EditorPrefs 键名常量
    private const string PREFS_KEY_PREFIX = "ExcelToFlatBuffer_";
    private const string KEY_EXCEL_FOLDER = PREFS_KEY_PREFIX + "ExcelFolderPath";
    private const string KEY_OUTPUT_PATH = PREFS_KEY_PREFIX + "OutputPath";
    private const string KEY_DATA_PATH = PREFS_KEY_PREFIX + "DataPathOutputPath";
    private const string KEY_CS_PATH = PREFS_KEY_PREFIX + "CsOutputPath";
    private const string KEY_FLATC_PATH = PREFS_KEY_PREFIX + "FlatcPath";
    private const string KEY_COPY_BYTES_PATH = PREFS_KEY_PREFIX + "CopyBytesPath";
    private const string KEY_FIELD_COMMENT_INDEX = PREFS_KEY_PREFIX + "FieldCommentIndex";
    private const string KEY_FIELD_NAME_INDEX = PREFS_KEY_PREFIX + "FieldNameIndex";
    private const string KEY_FIELD_TYPE_INDEX = PREFS_KEY_PREFIX + "FieldTypeIndex";
    private const string KEY_DATA_START_INDEX = PREFS_KEY_PREFIX + "DataStartIndex";

    // 默认值
    private string defaultExcelFolderPath = "Assets/../excels";
    private string defaultOutputPath = "Assets/Scripts";
    private string defaultDataPathOutputPath = "Assets/AutoGenerated/FlatBuffersDataFile";
    private string defaultCsOutputPath = "Assets/AutoGenerated/Scripts";
    private string defaultFlatcPath = Application.dataPath + "/../_Tools/flatc.exe";
    private string defaultCopyBytesPath = Application.dataPath + "/Resources/fb";
    private int defaultFieldCommentIndex = 3;
    private int defaultFieldNameIndex = 5;
    private int defaultFieldTypeIndex = 6;
    private int defaultDataStartIndex = 7;

    // 属性封装，关联 EditorPrefs
    public string excelFolderPath
    {
        get => EditorPrefs.GetString(KEY_EXCEL_FOLDER, defaultExcelFolderPath);
        set => EditorPrefs.SetString(KEY_EXCEL_FOLDER, value);
    }

    public string outputPath
    {
        get => EditorPrefs.GetString(KEY_OUTPUT_PATH, defaultOutputPath);
        set => EditorPrefs.SetString(KEY_OUTPUT_PATH, value);
    }

    public string dataPathOutputPath
    {
        get => EditorPrefs.GetString(KEY_DATA_PATH, defaultDataPathOutputPath);
        set => EditorPrefs.SetString(KEY_DATA_PATH, value);
    }

    public string csOutputPath
    {
        get => EditorPrefs.GetString(KEY_CS_PATH, defaultCsOutputPath);
        set => EditorPrefs.SetString(KEY_CS_PATH, value);
    }

    public string flatcPath
    {
        get => EditorPrefs.GetString(KEY_FLATC_PATH, defaultFlatcPath);
        set => EditorPrefs.SetString(KEY_FLATC_PATH, value);
    }

    public string copyBytesPath
    {
        get => EditorPrefs.GetString(KEY_COPY_BYTES_PATH, defaultCopyBytesPath);
        set => EditorPrefs.SetString(KEY_COPY_BYTES_PATH, value);
    }

    public int fieldCommentIndex
    {
        get => EditorPrefs.GetInt(KEY_FIELD_COMMENT_INDEX, defaultFieldCommentIndex);
        set => EditorPrefs.SetInt(KEY_FIELD_COMMENT_INDEX, value);
    }

    public int fieldNameIndex
    {
        get => EditorPrefs.GetInt(KEY_FIELD_NAME_INDEX, defaultFieldNameIndex);
        set => EditorPrefs.SetInt(KEY_FIELD_NAME_INDEX, value);
    }

    public int fieldTypeIndex
    {
        get => EditorPrefs.GetInt(KEY_FIELD_TYPE_INDEX, defaultFieldTypeIndex);
        set => EditorPrefs.SetInt(KEY_FIELD_TYPE_INDEX, value);
    }

    public int dataStartIndex
    {
        get => EditorPrefs.GetInt(KEY_DATA_START_INDEX, defaultDataStartIndex);
        set => EditorPrefs.SetInt(KEY_DATA_START_INDEX, value);
    }

    [NonSerialized]
    public bool flatcAvailable = false;

    // 重置为默认值的方法
    public void ResetToDefaults()
    {
        excelFolderPath = defaultExcelFolderPath;
        outputPath = defaultOutputPath;
        dataPathOutputPath = defaultDataPathOutputPath;
        csOutputPath = defaultCsOutputPath;
        flatcPath = defaultFlatcPath;
        copyBytesPath = defaultCopyBytesPath;
        fieldCommentIndex = defaultFieldCommentIndex;
        fieldNameIndex = defaultFieldNameIndex;
        fieldTypeIndex = defaultFieldTypeIndex;
        dataStartIndex = defaultDataStartIndex;
    }

    // 清除所有保存的设置
    public static void ClearAllSettings()
    {
        EditorPrefs.DeleteKey(KEY_EXCEL_FOLDER);
        EditorPrefs.DeleteKey(KEY_OUTPUT_PATH);
        EditorPrefs.DeleteKey(KEY_DATA_PATH);
        EditorPrefs.DeleteKey(KEY_CS_PATH);
        EditorPrefs.DeleteKey(KEY_FLATC_PATH);
        EditorPrefs.DeleteKey(KEY_COPY_BYTES_PATH);
        EditorPrefs.DeleteKey(KEY_FIELD_COMMENT_INDEX);
        EditorPrefs.DeleteKey(KEY_FIELD_NAME_INDEX);
        EditorPrefs.DeleteKey(KEY_FIELD_TYPE_INDEX);
        EditorPrefs.DeleteKey(KEY_DATA_START_INDEX);
    }
}

[Serializable]
public class ExcelTableData
{
    public string tableName;
    public string workbookName;
    public string[] fieldComments;
    public string[] fieldNames;
    public string[] fieldTypes;
    public string[][] dataRows;
}